package com.example.myapp.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

//The colors have been generated by Material Theme Builder at https://material-foundation.github.io/material-theme-builder/
// LIGHT THEME COLORS - STANDARD CONTRAST
// These colors define the light theme with standard contrast levels following Material Design 3

val primaryLight = Color(0xFF5A631E) // Main brand color - dark green
val onPrimaryLight = Color(0xFFFFFFFF) // Text color on primary surfaces - white
val primaryContainerLight = Color(0xFFDFE995) // Background for primary containers - light green
val onPrimaryContainerLight = Color(0xFF434B06) // Text color on primary containers - dark green
val secondaryLight = Color(0xFF596420) // Secondary brand color - slightly different green
val onSecondaryLight = Color(0xFFFFFFFF) // Text color on secondary surfaces - white
val secondaryContainerLight = Color(0xFFDCEA97) // Background for secondary containers - light green
val onSecondaryContainerLight = Color(0xFF414B08) // Text color on secondary containers - dark green
val tertiaryLight = Color(0xFF5A631F) // Tertiary accent color - green
val onTertiaryLight = Color(0xFFFFFFFF) // Text color on tertiary surfaces - white
val tertiaryContainerLight = Color(0xFFDEEA96) // Background for tertiary containers - light green
val onTertiaryContainerLight = Color(0xFF424B06) // Text color on tertiary containers - dark green
val errorLight = Color(0xFFBA1A1A) // Error color - red
val onErrorLight = Color(0xFFFFFFFF) // Text color on error surfaces - white
val errorContainerLight = Color(0xFFFFDAD6) // Background for error containers - light red
val onErrorContainerLight = Color(0xFF93000A) // Text color on error containers - dark red
val backgroundLight = Color(0xFFFCFAED) // Main background color - very light cream
val onBackgroundLight = Color(0xFF1B1C14) // Text color on background - dark
val surfaceLight = Color(0xFFFBFAED) // Surface color for cards and containers - light cream
val onSurfaceLight = Color(0xFF1B1C15) // Text color on surfaces - dark
val surfaceVariantLight = Color(0xFFE4E3D2) // Alternative surface color - light gray
val onSurfaceVariantLight = Color(0xFF47483B) // Text color on surface variants - dark gray
val outlineLight = Color(0xFF77786A) // Border and divider color - medium gray
val outlineVariantLight = Color(0xFFC8C7B7) // Alternative border color - light gray
val scrimLight = Color.Unspecified // Overlay color - unspecified for light theme
val inverseSurfaceLight = Color(0xFF303129) // Inverse surface color - dark
val inverseOnSurfaceLight = Color(0xFFF3F1E4) // Text color on inverse surfaces - light
val inversePrimaryLight = Color(0xFFC2CD7C) // Inverse primary color - light green
val surfaceDimLight = Color(0xFFDCDACE) // Dimmed surface color - muted cream
val surfaceBrightLight = Color(0xFFFBFAED) // Bright surface color - light cream
val surfaceContainerLowestLight = Color(0xFFFFFFFF) // Highest elevation surface - white
val surfaceContainerLowLight = Color(0xFFF6F4E7) // Low elevation surface - very light cream
val surfaceContainerLight = Color(0xFFF0EEE2) // Standard elevation surface - light cream
val surfaceContainerHighLight = Color(0xFFEAE9DC) // High elevation surface - medium cream
val surfaceContainerHighestLight = Color(0xFFE4E3D6) // Highest elevation surface - darker cream


val primaryDark = Color(0xFFC2CD7C) // Light green primary for dark theme
val onPrimaryDark = Color(0xFF2D3400) // Dark text on primary surfaces
val primaryContainerDark = Color(0xFF434B06) // Dark green container background
val onPrimaryContainerDark = Color(0xFFDFE995) // Light text on primary containers
val secondaryDark = Color(0xFFC0CE7D) // Light green secondary for dark theme
val onSecondaryDark = Color(0xFF2C3400) // Dark text on secondary surfaces
val secondaryContainerDark = Color(0xFF414B08) // Dark green secondary container
val onSecondaryContainerDark = Color(0xFFDCEA97) // Light text on secondary containers
val tertiaryDark = Color(0xFFC2CD7C) // Light green tertiary for dark theme
val onTertiaryDark = Color(0xFF2D3400) // Dark text on tertiary surfaces
val tertiaryContainerDark = Color(0xFF424B06) // Dark green tertiary container
val onTertiaryContainerDark = Color(0xFFDEEA96) // Light text on tertiary containers
val errorDark = Color(0xFFFFB4AB) // Light red error for dark theme
val onErrorDark = Color(0xFF690005) // Dark text on error surfaces
val errorContainerDark = Color(0xFF93000A) // Dark red error container
val onErrorContainerDark = Color(0xFFFFDAD6) // Light text on error containers
val backgroundDark = Color(0xFF13140D) // Very dark background
val onBackgroundDark = Color(0xFFE4E3D6) // Light text on background
val surfaceDark = Color(0xFF13140D) // Dark surface
val onSurfaceDark = Color(0xFFE4E3D6) // Light text on surfaces
val surfaceVariantDark = Color(0xFF47483B) // Dark surface variant
val onSurfaceVariantDark = Color(0xFFC8C7B7) // Light text on surface variants
val outlineDark = Color(0xFF919283) // Light outline for dark theme
val outlineVariantDark = Color(0xFF47483B) // Dark outline variant
val scrimDark = Color.Unspecified // Overlay color - unspecified for dark theme
val inverseSurfaceDark = Color(0xFFE4E3D6) // Light inverse surface
val inverseOnSurfaceDark = Color(0xFF303129) // Dark text on inverse surfaces
val inversePrimaryDark = Color(0xFF5A631E) // Dark inverse primary
val surfaceDimDark = Color(0xFF13140D) // Dark dim surface
val surfaceBrightDark = Color(0xFF393A31) // Bright surface for dark theme
val surfaceContainerLowestDark = Color(0xFF0E0F08) // Lowest elevation surface - very dark
val surfaceContainerLowDark = Color(0xFF1B1C15) // Low elevation surface - dark
val surfaceContainerDark = Color(0xFF1F2018) // Standard elevation surface - medium dark
val surfaceContainerHighDark = Color(0xFF2A2B22) // High elevation surface - lighter dark
val surfaceContainerHighestDark = Color(0xFF35352D) // Highest elevation surface - lightest dark

// EXTENDED COLORS
// Additional colors that extend beyond the Material Design 3 color system for specific app needs

@Immutable
/**
 * ExtendedColors
 *
 * Data class representing [TODO: Add description]
 */
data class ExtendedColors(
   val white: Color = Color(0xFFFFFFFF), // Pure white - used for backgrounds and text
   val transparent: Color = Color(0x00000000), // Transparent - used for overlays and effects
   val green: Color = Color(0xFF00FF00), // Pure green - used for success states and indicators
   val blue: Color = Color(0xFF0000FF), // Pure blue - used for links and interactive elements
   val black: Color = Color(0xFF000000), // Pure black - used for text and borders
   val orange: Color = Color(0xFFFFD700), // Pure orange - used for price ratings
   val customColor1: Color = Color(0xFF2196F3),
   val customColor2: Color = Color(0xFF9C27B0),
   val customColor3: Color = Color(0xFFE91E63),
   val customColor4: Color = Color(0xFFFF9800),
   val customColor5: Color = Color(0xFF4CAF50),

//   gradient colors
//   special offer gradient color combinations
//   gradient 1
   val customColor6: Color = Color(0xFFFF6B35),
   val customColor7: Color = Color(0xFFFF8E53),

//   gradient 2
   val customColor9: Color = Color(0xFF667eea),
   val customColor10: Color = Color(0xFF764ba2),

//   gradient 3
   val customColor11: Color = Color(0xFF11998e),
   val customColor12: Color = Color(0xFF38ef7d),
   val customColor13: Color =  Color(0xFFFFD700),

   val customColor14: Color = Color(0xFFF57F17),
   val customColor15: Color = Color(0xFFFFF9C4),
   val customColor16: Color = Color(0xFF00A8E1),
   val customColor17: Color = Color(0xFF8BC34A),

   val purple: Color = Color(0xFF800080),
   val lightPurple: Color = Color(0xFF9C27B0),
   val pink: Color = Color(0xFFFFC0CB),
   val pureOrange: Color = Color(0xFFFFA500),
   val brown: Color = Color(0xFFA52A2A),
   val gray: Color = Color(0xFF757575),
   val red: Color = Color(0xFFE53935),
   val favRed: Color = Color(0xFFFF4444),
   val bgWhite: Color = Color(0xFFFFEBEE),
   val yellow: Color = Color(0xFFFFEB3B)
)

// CompositionLocal for providing ExtendedColors throughout the composition tree
// This allows any composable to access these extended colors without explicitly passing them
val LocalColors = staticCompositionLocalOf { ExtendedColors() }

// Extension property on MaterialTheme that provides easy access to ExtendedColors
// Usage: val colors = MaterialTheme.colors
// This property is marked as @Composable and @ReadOnlyComposable for proper Compose integration
val colors: ExtendedColors
   @Composable
   @ReadOnlyComposable
   get() = LocalColors.current

 